name: Qualidade de Código

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    name: Análise de Código
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install flake8 mypy black isort
      shell: bash
    
    - name: Verificar formatação com Black
      run: |
        black --check src/ tests/
      continue-on-error: true
    
    - name: Verificar ordenação de imports com isort
      run: |
        isort --check-only --profile black src/ tests/
      continue-on-error: true
    
    - name: Análise estática com flake8
      run: |
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
    
    - name: Verificar tipagem com mypy
      run: |
        mypy --ignore-missing-imports src/
      continue-on-error: true

  security:
    name: Análise de Segurança
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit safety
      shell: bash
    
    - name: Verificar problemas de segurança com Bandit
      run: |
        bandit -r src/ -c pyproject.toml
      continue-on-error: true
    
    - name: Verificar vulnerabilidades conhecidas
      run: |
        safety check
      continue-on-error: true 