name: Cobertura de Código

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  codecov:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pytest pytest-cov
      shell: pwsh
    
    - name: Criar diretórios para teste
      run: |
        New-Item -Path "tests/data" -ItemType Directory -Force
        New-Item -Path "tests/output" -ItemType Directory -Force
        New-Item -Path "logs/validation" -ItemType Directory -Force
      shell: pwsh
    
    - name: Executar testes com cobertura
      run: |
        python -m pytest --cov=noki tests/ --cov-report=xml
      shell: pwsh
    
    - name: Enviar para Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true 