name: GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .

      - name: Build Windows package
        run: |
          python build.py --info
          python build.py --no-console

      - name: Build macOS package
        run: |
          python build.py --info
          SYSTEM=darwin PLATFORM=macos python build.py --no-console

      - name: Build Linux package
        run: |
          python build.py --info
          SYSTEM=linux PLATFORM=linux python build.py --no-console

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: false 