name: Publicar Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Construir e Publicar
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install -e .

      - name: Construir pacote
        run: |
          python -m build

      - name: Criar Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 