name: Basic Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run Basic Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pytest
      shell: bash
    
    - name: Create test directories
      run: |
        mkdir -p tests/data
        mkdir -p tests/output
        mkdir -p logs/validation
      shell: bash
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
      shell: bash 